package com.grimidk.formicempire.classes.infrasctructure.repositories;

import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.swing.ImageIcon;

/**
 * Loads colony building room / menu sprites from {@code sprites/buildings/rooms/} (PascalCase PNGs).
 * Placeholders are generated by {@code scripts/sync_room_placeholders.sh} from {@code icons/} until
 * final art replaces them. Kept separate from {@link GameConstants} so {@link GameUnlocks} static
 * init does not cycle.
 */
public final class BuildingSpriteResources {

    /** Expected edge length of {@code sprites/buildings/rooms/*.png} (placeholders are synced to this size). */
    public static final int ROOM_ICON_PX = 48;

    private static final Map<String, ImageIcon> CACHE = new HashMap<>();

    private BuildingSpriteResources() {
    }

    public static ImageIcon roomTier(String chainKey, int level) {
        if (chainKey == null) {
            return null;
        }
        int tier = Math.max(0, Math.min(3, level));
        String chain = pascalSegment(chainKey);
        return icon("sprites/buildings/rooms/" + chain + "L" + tier + ".png");
    }

    public static ImageIcon passiveRoom(String passiveKey) {
        if (passiveKey == null || passiveKey.isEmpty()) {
            return null;
        }
        return icon("sprites/buildings/rooms/Passive" + pascalSegment(passiveKey) + ".png");
    }

    private static String pascalSegment(String key) {
        return Character.toUpperCase(key.charAt(0)) + key.substring(1);
    }

    private static ImageIcon icon(String classpathRelativePath) {
        if (CACHE.containsKey(classpathRelativePath)) {
            return CACHE.get(classpathRelativePath);
        }
        URL url = resolveResourceUrl(classpathRelativePath);
        if (url == null) {
            System.err.println("BuildingSpriteResources: missing " + classpathRelativePath);
            return null;
        }
        ImageIcon ic = new ImageIcon(url);
        CACHE.put(classpathRelativePath, ic);
        return ic;
    }

    private static URL resolveResourceUrl(String path) {
        URL u = tryUrl(path);
        if (u != null) {
            return u;
        }
        String alt = alternateFilenameFirstLetterCase(path);
        if (alt != null && !alt.equals(path)) {
            u = tryUrl(alt);
        }
        return u;
    }

    private static URL tryUrl(String classpathRelativePath) {
        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        if (cl != null) {
            URL u = cl.getResource(classpathRelativePath);
            if (u != null) {
                return u;
            }
        }
        return BuildingSpriteResources.class.getResource("/" + classpathRelativePath);
    }

    private static String alternateFilenameFirstLetterCase(String path) {
        int sep = path.lastIndexOf('/');
        int nameStart = sep + 1;
        if (nameStart >= path.length()) {
            return null;
        }
        char c = path.charAt(nameStart);
        if (!Character.isLetter(c)) {
            return null;
        }
        char toggled = Character.isUpperCase(c) ? Character.toLowerCase(c) : Character.toUpperCase(c);
        return path.substring(0, nameStart) + toggled + path.substring(nameStart + 1);
    }
}
